server:
    port: 9797
    error:
        include-message: always

spring:
    datasource:
        password: yiman
        url: jdbc:postgresql://localhost:5433/jwt
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
app:
    jwt:
        secret: java10

