server:
    port: 9797
spring:
    datasource:
        password: yiman
        url: jdbc:postgresql://localhost:5433/jwt
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
        show-sql: true
